# Project: extrator
# Makefile created by Dev-C++ 4.9.7.0

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = extrator.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" 
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/c++" 
BIN  = extrator.exe
CXXFLAGS = $(INCS) 
CFLAGS = $(INCS) 

.PHONY: all all-before all-after clean clean-custom

all: all-before extrator.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(OBJ) -o "extrator.exe" $(LIBS) $(CXXFLAGS)

extrator.o: extrator.cpp
	$(CPP) -c extrator.cpp -o extrator.o $(CXXFLAGS)
